server {
    listen 3000;
    
    location / {
        root /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is the "magic" for SPAs:
        # It tells Nginx: if you can't find the file, serve index.html
        try_files $uri $uri/ /index.html;
    }
}