apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # For local development, we can use the hostPath storage class, which allows us to use a directory on the host machine as storage for our PVC. This is not recommended for production environments, but it works well for local development and testing.
  storageClassName: hostpath
