/* tslint:disable */
/* eslint-disable */
/**
 * Values API
 * API for managing calculated values with Postgres and Redis.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CalculateIndexValue200Response {
    'message'?: string;
}
export interface CalculateIndexValueRequest {
    /**
     * The index to calculate
     */
    'index'?: string;
}
export interface GetAllIndices200ResponseInner {
    'number'?: number;
}

/**
 * FibApi - axios parameter creator
 */
export const FibApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Submit a new index
         * @param {CalculateIndexValueRequest} calculateIndexValueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateIndexValue: async (calculateIndexValueRequest: CalculateIndexValueRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'calculateIndexValueRequest' is not null or undefined
            assertParamExists('calculateIndexValue', 'calculateIndexValueRequest', calculateIndexValueRequest)
            const localVarPath = `/api/indices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calculateIndexValueRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all indices from Postgres
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIndices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/indices/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current indices and values from Redis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvailableIndexValues: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/indices/values`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FibApi - functional programming interface
 */
export const FibApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FibApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Submit a new index
         * @param {CalculateIndexValueRequest} calculateIndexValueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calculateIndexValue(calculateIndexValueRequest: CalculateIndexValueRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalculateIndexValue200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calculateIndexValue(calculateIndexValueRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FibApi.calculateIndexValue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all indices from Postgres
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllIndices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetAllIndices200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllIndices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FibApi.getAllIndices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current indices and values from Redis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAvailableIndexValues(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAvailableIndexValues(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FibApi.getAvailableIndexValues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHealthCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHealthCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FibApi.getHealthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FibApi - factory interface
 */
export const FibApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FibApiFp(configuration)
    return {
        /**
         * 
         * @summary Submit a new index
         * @param {CalculateIndexValueRequest} calculateIndexValueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateIndexValue(calculateIndexValueRequest: CalculateIndexValueRequest, options?: RawAxiosRequestConfig): AxiosPromise<CalculateIndexValue200Response> {
            return localVarFp.calculateIndexValue(calculateIndexValueRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all indices from Postgres
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllIndices(options?: RawAxiosRequestConfig): AxiosPromise<Array<GetAllIndices200ResponseInner>> {
            return localVarFp.getAllIndices(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current indices and values from Redis
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvailableIndexValues(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.getAvailableIndexValues(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealthCheck(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getHealthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FibApi - object-oriented interface
 */
export class FibApi extends BaseAPI {
    /**
     * 
     * @summary Submit a new index
     * @param {CalculateIndexValueRequest} calculateIndexValueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public calculateIndexValue(calculateIndexValueRequest: CalculateIndexValueRequest, options?: RawAxiosRequestConfig) {
        return FibApiFp(this.configuration).calculateIndexValue(calculateIndexValueRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all indices from Postgres
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllIndices(options?: RawAxiosRequestConfig) {
        return FibApiFp(this.configuration).getAllIndices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current indices and values from Redis
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAvailableIndexValues(options?: RawAxiosRequestConfig) {
        return FibApiFp(this.configuration).getAvailableIndexValues(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHealthCheck(options?: RawAxiosRequestConfig) {
        return FibApiFp(this.configuration).getHealthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



