name: CI/CD Pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master] # Runs when a PR is opened targeting master and catches error if any

# This sets the flag globally for the whole workflow to use Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # --- STAGE 1: Testing ---
  test-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      # Test the Client (UI)
      - name: Install & Test Client
        working-directory: ./client
        run: |
          npm ci
          npx tsc --noEmit
          npm run test:run -- --reporter=github-actions

      # NEW STEP: The Production Build Check for client
      - name: Build Client
        working-directory: ./client
        run: npm run build
        env:
          NODE_ENV: production
          VITE_API_BASE_URL: /api

      # NEW STEP: The Production Build Check for server
      - name: Build Server
        working-directory: ./server
        run: |
          npm ci --include=dev
          npm run build
        env:
          NODE_ENV: production

      # NEW STEP: The Production Build Check for worker
      - name: Build Worker
        working-directory: ./worker
        run: |
          npm ci --include=dev
          npm run build
        env:
          NODE_ENV: production

  # --- STAGE 2: Build and Push (Only runs if Stage 1 passes) ---
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test-and-verify # <--- THIS IS THE MAGIC KEY: It prevents building if tests fail
    runs-on: ubuntu-latest
    # --- THIS PART IS KEY ---
    # These variables will be visible to the 'docker compose' command below
    # env:
    #   POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    #   PG_USER: ${{ secrets.PG_USER }}
    #   PG_HOST: ${{ secrets.PG_HOST }}
    #   PG_DATABASE: ${{ secrets.PG_DATABASE }}
    #   PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
    #   PG_PORT: ${{ secrets.PG_PORT }}
    #   REDIS_HOST: ${{ secrets.REDIS_HOST }}
    #   REDIS_PORT: ${{ secrets.REDIS_PORT }}
    #   VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    steps:
      # 1. Pull down your repository code so the workflow can access the Dockerfiles
      - name: Checkout code
        uses: actions/checkout@v6

      # 2. Authenticate into Docker Hub using repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx for faster, optimized image caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and Push BACKEND (Server) Image
      - name: Build & Push Server Service
        uses: docker/build-push-action@v5
        with:
          context: ./server # Path to directory containing server Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 # Build multi-arch images for broader compatibility
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-api:${{ github.sha }}
      # 5. Build and Push FRONTEND (Client) Image
      - name: Build & Push Client Service
        uses: docker/build-push-action@v5
        with:
          context: ./client # Path to directory containing client Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 # Build multi-arch images for broader compatibility
          build-args: |
            VITE_API_BASE_URL=/api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-ui:${{ github.sha }}
      # 6. Build and Push BACKEND (Worker) Image
      - name: Build & Push Worker Service
        uses: docker/build-push-action@v5
        with:
          context: ./worker # Path to directory containing worker Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 # Build multi-arch images for broader compatibility
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-worker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-worker:${{ github.sha }}
  # --- STAGE 3: True Kubernetes Production Deployment to DOKS---
  deploy-to-doks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build-and-push # <--- THIS IS THE MAGIC KEY: It prevents deploying if build fails
    runs-on: ubuntu-latest
    steps:
      # 1. Pull down your repository context (.yaml manifests)
      - name: Checkout code
        uses: actions/checkout@v6
      # 2. Install the DigitalOcean CLI manager tool natively on the GitHub's machine
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # 3. # Downloads the secure access key (~/.kube/config) to GitHub's machine
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save learning-k8s-cluster
      # 4. Apply your core system maps and environment declarations
      - name: Deploy Core Manifests
        run: |
          kubectl apply -f k8s/config.yaml
          kubectl apply -f k8s/
      # 5. Inject the unique image SHA to trigger a clean rolling update
      - name: Rollout Application Images
        run: |
          kubectl set image deployment/server-deployment server=${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-api:${{ github.sha }}
          kubectl set image deployment/client-deployment client=${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-ui:${{ github.sha }}
          kubectl set image deployment/worker-deployment worker=${{ secrets.DOCKERHUB_USERNAME }}/k8s-multi-container-app-worker:${{ github.sha }}
